# monitoring/prometheus/prometheus.yml
global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "api-services"
    static_configs:
      - targets: ["api-services:8000"]
    metrics_path: "/metrics"
    scrape_interval: 5s

  - job_name: "ml-services"
    static_configs:
      - targets: ["ml-services:8001"]
    metrics_path: "/metrics"
    scrape_interval: 10s

  - job_name: "kafka"
    static_configs:
      - targets: ["kafka:9092"]
    metrics_path: "/metrics"

  - job_name: "redis"
    static_configs:
      - targets: ["redis:6379"]

  - job_name: "postgres"
    static_configs:
      - targets: ["postgres:5432"]

  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]
